# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sK1NQ9YRB7sPujtUJ9jDQwIe8SOsJqSc
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.preprocessing import StandardScaler, MinMaxScaler

from scipy.stats import norm
from scipy import stats

housing = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/Ames_Housing_Data1.tsv", sep='\t')
# housing = pd.read_csv("/home/mohammedah10/Downloads/IBMSpecialization/ExploratoryDataAnalysis/Week3/nJoMNLPqT9yaDDSz6n_cow_d165c3f05e87451e8700f88acaec39e7_01d_DEMO_Feature_Engineering/data/Ames_Housing_Data.tsv", sep='\t')
housing.head(10)

housing.info()

"""lets use 'describe()' to show count, min, max of the 'SalePrice' attribute"""

housing['SalePrice'].describe()

"""The min value is greather than 0 and great diffenrence between it and 25th percentile. The max value is greater than 75th percentile, maing our data not
normally distributed (an important assumption for regression analysis), will check for normalit using LogTransformation
"""

housing["Sale Condition"].value_counts().describe()
# housing['Sale Condition'].describe()

"""## **Looking for correlation**

Before proceeding with the data cleaning, it is useful to establish a correlation between the response variable (in our case the sale price) and other predictor variables, as some of them might not have any major impact in determining the price of the house and will not be used in the analysis.  There are many ways to discover correlation between the target variable and the rest of the features. Building pair plots, scatter plots, heat maps, and a correlation matrixes are the most common ones. Below, we will use the `corr()` function to list the top features based on the [pearson correlation coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01) (measures how closely two sequences of numbers are correlated). Correlation coefficient can only be calculated on the numerical attributes (floats and integers), therefore, only the numeric attributes will be selected.

"""

house_nums = housing.select_dtypes(include=['float64', 'int64'])
house_nums_corr = house_nums.corr()['SalePrice'][:-1]   # the -1 means the latest row is SalePrice
top_features = house_nums_corr[abs(house_nums_corr) > 0.5].sort_values(ascending=False) # DIsplay pearson correlation coeffiecint greather than 0.5
print("There is {} strongly correlated values with SalePrice:\n{}".format(len(top_features), top_features))

for i in range(0, len(house_nums.columns), 5):
    sns.pairplot(data=house_nums,
                x_vars=house_nums.columns[i:i+5],
                y_vars=['SalePrice'])

"""From Pearsons Correlation Coefficients and pair plots, we can draw some conclusions about the features that are most strongly correlated to the 'SalePrice'. They are: 'Overall Qual', 'Gr Liv Area', 'Garage Cars', 'Garage Area', and others.

## **Log Transformation**

we are going to inspect whether our 'SalePrice' data are normally distributed. The assumption of the normal distribution must be met in order to perform any type of regression analysis. There are several ways to check for this assumption, however here, we will use the visual method, by plotting the 'SalePrice' distribution using the `distplot()` function from the `seaborn` library.
"""

saleprice_untrransformed = sns.displot(housing['SalePrice'])

"""As the plot shows, our 'SalePrice' deviates from the normal distribution. It has a longer tail to the right, so we call it a positive skew. In statistics *skewness* is a measure of asymmetry of the distribution. In addition to skewness, there is also a kurtosis, parameter which refers to the pointedness of a peak in the distribution curve. Both skewness and kurtosis are frequently used together to characterize the distribution of data.

"""

# Here, we can simply use the `skew()` function to calculate our skewness level of the `SalePrice`.
print("Skewness: %f" % housing['SalePrice'].skew())

"""The range of skewness for a fairly symmetrical bell curve distribution is between -0.5 and 0.5; moderate skewness is -0.5 to -1.0 and 0.5 to 1.0; and highly skewed distribution is < -1.0 and > 1.0. In our case, we have ~1.7, so it is considered  highly skewed data.

Now, we can try to transform our data, so it looks more normally distributed. We can use the `np.log()` function from the `numpy` library to perform log transform. This [documentation](https://numpy.org/doc/stable/reference/generated/numpy.log.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01) contains more information about the numpy log transform.

"""

log_transform = np.log(housing['SalePrice'])

sp_transformed = sns.displot(log_transform)

print("Skewness: %f" % log_transform.skew())

"""The log method transformed the 'SalePrice' distribution into a more symmetrical bell curve and the skewness level now is -0.01, well within the range.

There are other ways to correct for skewness of the data. For example, Square Root Transform (`np.sqrt`) and the Box-Cox Transform (`stats.boxcox` from the `scipy stats` library). To learn more about these two methods, please check out this [article](https://towardsdatascience.com/top-3-methods-for-handling-skewed-data-1334e0debf45?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01).

"""

LotArea = sns.distplot(housing["Lot Area"])

print("Skewness: %f" % housing['Lot Area'].skew())

LotAreaTransformed = np.log(housing["Lot Area"])

LATransform = sns.displot(LotAreaTransformed)

print("Skewness: %f" % LotAreaTransformed.skew())

"""## Handling Missing Values

### Finding the Missing Values
For easier detection of missing values, pandas provides the `isna()`, `isnull()`, and `notna()` functions. For more information on pandas missing values please check out this [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01).

To summarize all the missing values in our dataset, we will use `isnull()` function. Then, we will add them all up, by using `sum()` function, sort them with `sort_values()` function, and plot the first 20 columns (as the majority of our missing values fall within first 20 columns), using the `bar plot` function from the `matplotlib` library.
"""

total = housing.isnull().sum().sort_values(ascending=False)
total_select = total.head(20)

total_select.plot(kind="bar", figsize = (8,6), fontsize = 10)

plt.xlabel("Columns", fontsize = 20)
plt.ylabel("Count", fontsize = 20)
plt.title("Total Missing Values", fontsize = 20)

"""There are three was to deal with missing values

1. Drop all the rows that are missing (N/A) using `dropna()`
2. Drop the entire feature(column) using `drop()`
3. Fill in the values with zeros, ones, mean, medians etc using `fillna()`.
"""

# dropna()
housing.dropna(subset=["Lot Frontage"])

# drop()
housing.drop("Lot Frontage", axis=1)

# fillna()
median = housing['Lot Frontage'].median()
median

housing['Lot Frontage'].fillna(median, inplace=True)

mean = housing['Mas Vnr Area'].mean()
mean

housing["Mas Vnr Area"].fillna(mean, inplace=True)

"""## Feature Scaling
feature scaling is a way to get the attributes of your data to have the same scale.

there are two common was to scale data

1. Normalzation

`Normalization` -> `MinMaxScaler` keeps the data atributes on the scale ranginig from 0 - 1, it is performed by subtracting the min value then dividing by max minuns min values `data - min/(max - min)`

`MinMaxScaler` in sklearn
"""

norm_data = MinMaxScaler().fit_transform(house_nums)
norm_data

"""2. Standardization
`Standardization` -> ensires the values have a zero mean and a unit variance it is performed by subtracting mean and dividing by standard deviation `data - mean/stardard-deviation`
"""

scaled_data = StandardScaler().fit_transform(house_nums)
scaled_data

scaled_sprice = StandardScaler().fit_transform(housing['SalePrice'].values.reshape(-1, 1))
scaled_sprice

"""## Handling Outliers

outliers in statistics are observation points that are distant frim the other points, it can be due to mistake in data collection or high variability in data points

there are many ways to discover outliers in data, 2 of them are uni-variate analysis (one varaible analysis) and multivariate analsis (multiple varaible analysis)

A box plot is a method for graphically depicting groups of numerical data through their quartiles. Box plots may also have lines extending vertically from the boxes (whiskers) indicating variability outside the upper and lower quartiles. Outliers may be plotted as individual points. To learn more about box plots please click [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.boxplot.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01).

### Univariate analysis
"""

sns.boxplot(x=housing['Lot Area'])

sns.boxplot(x=housing['SalePrice'])

"""### Multivariate Analysis"""

housing.plot.scatter(x="Gr Liv Area", y="SalePrice")

"""### delete outliers"""

housing.sort_values(by="Gr Liv Area", ascending=False)[:2]

outliers_dropped = housing.drop(housing.index[[1498,2180]])

new_plot = outliers_dropped.plot.scatter(x='Gr Liv Area', y='SalePrice')

sns.boxplot(x=housing['Lot Area'])
price_lot = housing.plot.scatter(x='Lot Area', y='SalePrice')
housing['Lot_Area_Stats'] = stats.zscore(housing['Lot Area'])
housing[['Lot Area','Lot_Area_Stats']].describe().round(3)
housing.sort_values(by = 'Lot Area', ascending = False)[:1]
lot_area_rem = housing.drop(housing.index[[957]])

"""## Z-Score Analysis

Z-score is another way to identify outliers mathematically. Z-score is the signed number of standard deviations by which the value of an observation or data point is above the mean value of what is being observed or measured. In another words, Z-score is the value that quantifies relationship between a data point and a standard deviation and mean values of a group of points. Data points which are too far from zero will be treated as the outliers. In most of the cases, a threshold of 3 or -3 is used. For example, if the Z-score value is greater than or less than 3 or -3 standard deviations respectively, that data point will be identified as a outlier.

"""

housing['LQFSF_Stats'] = stats.zscore(housing['Low Qual Fin SF'])
housing[['Low Qual Fin SF','LQFSF_Stats']].describe().round(3)

"""The scaled results show a mean of 0.000 and a standard deviation of 1.000, indicating that the transformed values fit the z-scale model. The max value of 22.878 is further proof of the presence of outliers, as it falls well above the z-score limit of +3."""